<?php

use App\Permissions;
use App\Sections;
use Illuminate\Database\Seeder;

class SectionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sections = array(
            array('id' => '1','name' => 'Dashboard','parent_id' => 'main','sort_order' => '1','route' => 'dashboardListing','icon' => 'fa fa-dashboard','show_on_sidebar' => 'yes','english' => 'Dashboard','action' => NULL,'created_at' => '2019-12-28 21:45:18','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '2','name' => 'App Settings','parent_id' => 'main','sort_order' => '2','route' => NULL,'icon' => 'glyphicon glyphicon-equalizer','show_on_sidebar' => 'yes','english' => 'App Settings','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '3','name' => 'Content Management','parent_id' => '2','sort_order' => '0','route' => 'contentManagementListing','icon' => 'glyphicon glyphicon-cog','show_on_sidebar' => 'yes','english' => 'Content Management','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '4','name' => 'Push Notification','parent_id' => 'main','sort_order' => '3','route' => 'pushNotificationListing','icon' => 'glyphicon glyphicon-envelope','show_on_sidebar' => 'yes','english' => 'Push Notification','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '5','name' => 'Add','parent_id' => '4','sort_order' => '0','route' => 'sendPushNotificationAdd','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Add','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '6','name' => 'Resend','parent_id' => '4','sort_order' => '1','route' => 'resend','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Resend','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '7','name' => 'Shows','parent_id' => 'main','sort_order' => '4','route' => 'showsListing','icon' => 'fa fa-video','show_on_sidebar' => 'yes','english' => 'Shows','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '8','name' => 'Add','parent_id' => '7','sort_order' => '0','route' => 'addShowAdd','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Add','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '9','name' => 'Edit','parent_id' => '7','sort_order' => '1','route' => 'editShow','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Edit','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '10','name' => 'Show Questions','parent_id' => '7','sort_order' => '2','route' => 'showQuestions','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Show Questions','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '11','name' => 'Subscribed Show','parent_id' => '7','sort_order' => '3','route' => 'subscribedShowUsers','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Subscribed Show','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '12','name' => 'Delete','parent_id' => '7','sort_order' => '4','route' => 'deleteShow','icon' => NULL,'show_on_sidebar' => 'no','english' => 'delete','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '13','name' => 'Show Live','parent_id' => '7','sort_order' => '5','route' => 'makeShowLive','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Show Live','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '14','name' => 'Validate team players','parent_id' => '7','sort_order' => '6','route' => 'validateTeamPlayers','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Validate team players','action' => 'validate_team_players','created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '15','name' => 'Add','parent_id' => '7','sort_order' => '3','route' => 'showQuestionAdd','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Add','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '16','name' => 'Edit','parent_id' => '7','sort_order' => '4','route' => 'showQuestionEdit','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Edit','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '17','name' => 'Subscriber notification','parent_id' => '7','sort_order' => '5','route' => 'subscriber_notification','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Subscriber notification','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '18','name' => 'Delete','parent_id' => '7','sort_order' => '6','route' => 'showQuestionDelete','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Delete','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '19','name' => 'System','parent_id' => 'main','sort_order' => '5','route' => '','icon' => 'fa fa-store','show_on_sidebar' => 'yes','english' => 'System','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '20','name' => 'Managers','parent_id' => '19','sort_order' => '0','route' => 'managersListing','icon' => NULL,'show_on_sidebar' => 'yes','english' => 'Managers','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '21','name' => 'System Sections','parent_id' => '19','sort_order' => '1','route' => 'sectionsListing','icon' => NULL,'show_on_sidebar' => 'yes','english' => 'System Sections','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '22','name' => 'Add manager','parent_id' => '20','sort_order' => '0','route' => 'addManagerAdd','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Add manager','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '23','name' => 'Edit Emanager','parent_id' => '20','sort_order' => '1','route' => 'editManager','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Edit Manager','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '24','name' => 'Add manager Type','parent_id' => '20','sort_order' => '2','route' => 'addManagerTypeAdd','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Add manager Type','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '25','name' => 'Edit Manager type','parent_id' => '20','sort_order' => '3','route' => 'editManagerType','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Edit Manager type','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '26','name' => 'Delete Manager type','parent_id' => '20','sort_order' => '4','route' => 'deleteManagerType','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Delete Manager type','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '27','name' => 'Add section','parent_id' => '21','sort_order' => '0','route' => 'addSection','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Add section','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '28','name' => 'Edit Section','parent_id' => '21','sort_order' => '0','route' => 'editSection','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Edit Section','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '29','name' => 'ReOrder Section','parent_id' => '21','sort_order' => '0','route' => 'reOrder','icon' => NULL,'show_on_sidebar' => 'no','english' => 'ReOrder Section','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '30','name' => 'App Section Listing','parent_id' => 'main','sort_order' => '6','route' => 'appSectionsListing','icon' => 'fa fa-th-large','show_on_sidebar' => 'yes','english' => 'App Section Listing','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '31','name' => 'Sort','parent_id' => '30','sort_order' => '0','route' => 'appSectionsSorting','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Sort','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '32','name' => 'Add','parent_id' => '30','sort_order' => '1','route' => 'addAppSectionsAdd','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Add','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '33','name' => 'edit','parent_id' => '30','sort_order' => '2','route' => 'editAppSections','icon' => NULL,'show_on_sidebar' => 'no','english' => 'edit','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '34','name' => 'Delete','parent_id' => '30','sort_order' => '3','route' => 'deleteAppSections
          ','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Delete','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '35','name' => 'Section show','parent_id' => '30','sort_order' => '3','route' => 'showsRelatedToSection','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Section show','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '36','name' => 'Section show sort','parent_id' => '30','sort_order' => '4','route' => 'sectionShowSorting','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Section show sort','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '37','name' => 'Banner show','parent_id' => 'main','sort_order' => '7','route' => 'bannerShowsListing','icon' => 'fa fa-tasks','show_on_sidebar' => 'yes','english' => 'Banner show','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '38','name' => 'Banner show sort','parent_id' => '37','sort_order' => '7','route' => 'bannerShowSorting','icon' => '','show_on_sidebar' => 'no','english' => 'Banner show list','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '39','name' => 'Live Shows','parent_id' => 'main','sort_order' => '7','route' => 'liveShowListing','icon' => 'fa fa-play','show_on_sidebar' => 'yes','english' => 'Live Shows','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '40','name' => 'Make show live','parent_id' => '39','sort_order' => '0','route' => 'makeShowLive','icon' => '','show_on_sidebar' => 'no','english' => 'Make show live','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '41','name' => 'Players','parent_id' => 'main','sort_order' => '8','route' => 'playersListing','icon' => 'fa fa-group','show_on_sidebar' => 'yes','english' => 'Players','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '42','name' => 'Add Player','parent_id' => '41','sort_order' => '0','route' => 'addPlayersAdd','icon' => 'fa fa-group','show_on_sidebar' => 'no','english' => 'Add Player','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '43','name' => 'Edit Players','parent_id' => '41','sort_order' => '1','route' => 'editPlayer','icon' => '','show_on_sidebar' => 'no','english' => 'Edit Players','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '44','name' => 'Delete Player','parent_id' => '41','sort_order' => '2','route' => 'deletePlayer','icon' => '','show_on_sidebar' => 'no','english' => 'Delete Player','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '45','name' => 'Teams','parent_id' => 'main','sort_order' => '9','route' => 'teamsListing','icon' => 'fa fa-user-friends','show_on_sidebar' => 'yes','english' => 'Teams','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '46','name' => 'Add team','parent_id' => '45','sort_order' => '0','route' => 'addTeamsAdd','icon' => '','show_on_sidebar' => 'no','english' => 'Add Team','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '47','name' => 'Edit Team','parent_id' => '45','sort_order' => '1','route' => 'editTeam','icon' => '','show_on_sidebar' => 'no','english' => 'Edit Team','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '48','name' => 'Delete team','parent_id' => '45','sort_order' => '2','route' => 'deletePlayer','icon' => '','show_on_sidebar' => 'no','english' => 'Delete Team','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '49','name' => 'Application Users','parent_id' => 'main','sort_order' => '10','route' => 'applicationUsersListing','icon' => 'fa fa-group','show_on_sidebar' => 'yes','english' => 'Application Users','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '50','name' => 'Add user','parent_id' => '49','sort_order' => '0','route' => 'addUser','icon' => '','show_on_sidebar' => 'no','english' => 'Add User','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '51','name' => 'Edit user','parent_id' => '49','sort_order' => '1','route' => 'editUserInfo','icon' => '','show_on_sidebar' => 'no','english' => 'Edit user','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '52','name' => 'Delete user','parent_id' => '49','sort_order' => '2','route' => 'deleteApplicationUsers','icon' => '','show_on_sidebar' => 'no','english' => 'Delete USer','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '53','name' => 'Active Block User','parent_id' => '49','sort_order' => '2','route' => 'active_block','icon' => '','show_on_sidebar' => 'no','english' => 'Active Block User','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '55','name' => 'Groups','parent_id' => 'main','sort_order' => '11','route' => 'groupsListing','icon' => 'fa fa-group','show_on_sidebar' => 'yes','english' => 'Groups','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '56','name' => 'Delete group','parent_id' => '55','sort_order' => '0','route' => 'deleteGroup','icon' => '','show_on_sidebar' => 'no','english' => 'Delete group','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '57','name' => 'Group Info','parent_id' => '55','sort_order' => '1','route' => 'groupInfo','icon' => '','show_on_sidebar' => 'no','english' => 'Group Info','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL),
            array('id' => '58','name' => 'Add Sections','parent_id' => '19','sort_order' => '1','route' => 'addSectionAdd','icon' => NULL,'show_on_sidebar' => 'no','english' => 'Add Sections','action' => NULL,'created_at' => '2019-12-29 09:01:59','updated_at' => '2021-07-14 15:22:21','created_by' => NULL,'updated_by' => NULL)
          );

            foreach ($sections as $section) {
                $matchThese=['id' => $section['id']];
                Sections::updateOrCreate($matchThese,$section);
            }
    }
}
